### ISSUE TITLE
Cmake Errors with OPen SSL 1.0.2

### ISSUE THREAD

**Issue by Davuk** [SkyFireArchives/SkyFireEMU_406a#954]
When using the 1.0.2 Version of OPen SSL with the \cmake\macros\findopensl.cmake script you get

CMake Error at cmake/macros/FindOpenSSL.cmake:211 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:57 (find_package)

Ref: http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-emulator-servers/wow-emu-questions-requests/513039-openssl-cmake-problem-ubuntu-server.html

**Comment by Davuk** [comment]
Sorry Wrong Bugtracker Delete pls
(Being Noob is hell)

**Comment by alterego21** [comment]
Derp duh Derp
